### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by cooler333** [chriseidhof/commonmark-swift#11]
``` bash
iMac:Project user$ pod install
Analyzing dependencies
Downloading dependencies
Installing CommonMark (0.24.1)
Installing cmark (0.24.1)
[!] /bin/bash -c 
set -e
echo `pwd`
sed -i '' 's/include <\(cmark.*\)>/include "\1"/' src/cmark.h
mkdir -p build; cd build && cmake -G Xcode ..

/Users/dima/Library/Caches/CocoaPods/Pods/Release/cmark/0.24.1-ec027
/bin/bash: line 4: cmake: command not found
```

**Comment by slashmo** [comment]
Hi @cooler333,
you just have to install `cmake` manually:

```
brew update
brew install cmake
```

After installing everything should work fine. 👍

**Comment by chriseidhof** [comment]
Thanks! Yes, unfortunately, that's the case now...

**Comment by cooler333** [comment]
what about binary file?

**Comment by chriseidhof** [comment]
What do you mean?

**Comment by cooler333** [comment]
instead of compile cmark code via cmake, you can attach compiled binary file to library, like Google does.

**Comment by chriseidhof** [comment]
Hm, I don't really want to maintain that, I think, but I'll think about it for the future, thanks!

**Comment by cooler333** [comment]
can't install via brew too. CommonMark: empty folder after "pod install", i should use swift package?

i use pod from cocoapods search
https://cocoapods.org/?q=commonmark

**Comment by cooler333** [comment]
podfile:
  pod 'CommonMark', '~> 0.0.0'

terminal:
pod install
Installing CommonMark 0.0.8 (was 0.24.1)

now files appears

**Comment by chriseidhof** [comment]
Hm, that seems to be an outdated version (0.0.8). 

We're currently using it ourselves with swift package, which works great for our use case.

**Comment by CaliosD** [comment]
Hi, @chriseidhof , sorry to trouble you. But I've just come across the similar issue.

Here's what I've done:
- cmake installed.(3.7.2)
- Tried both `pod 'CommonMark', '~> 0.24.1'(newest version in cocoapods.org) ` and `pod 'CommonMark'`, but only to get empty Pods/CommonMark folder in Xcode project.
- Tried `pod 'CommonMark', '~> 0.0.0'` mentioned above by @cooler333  and got files with tons of errors. @_@

I wonder where I did wrong and how to fix it to get the correct files.
Thanks for your attention and time. :]

**Comment by chriseidhof** [comment]
Hi @CaliosD, have you tried using it with Swift Package Manager?
