### ISSUE TITLE
No CMAKE_CXX_COMPILER could be found, despite compiler source compilations succeeded.

### ISSUE THREAD

**Issue by ishaanSejwal** [chriseidhof/commonmark-swift#14]
I tried `pod install` and my podfile simply has `pod 'CommonMark'`

But I get `No CMAKE_CXX_COMPILER could be found` despite build succeeded when it compiled compiler identification source for C/CXX

===`pod install`===
Re-creating CocoaPods due to major version update.
Analyzing dependencies
Downloading dependencies
Installing CommonMark (0.24.0)
Installing cmark (0.24.0)
[!] /bin/bash -c 
set -e
echo `pwd`
sed -i '' 's/include <\(cmark.*\)>/include "\1"/' src/cmark.h
mkdir -p build; cd build && cmake -G Xcode ..

/Users/ishaanSejwal/Library/Caches/CocoaPods/Pods/Release/cmark/0.24.0-20849
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Configuring incomplete, errors occurred!
See also "/Users/ishaanSejwal/Library/Caches/CocoaPods/Pods/Release/cmark/0.24.0-20849/build/CMakeFiles/CMakeOutput.log".
CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_CXX_COMPILER could be found.
===`pod install` finished===

Please find CMakeOutput.txt file created from CMakeOutput.log contents attached.
[CMakeOutput.txt](https://github.com/chriseidhof/commonmark-swift/files/686686/CMakeOutput.txt)

**Comment by chriseidhof** [comment]
Hi,

You need to install cmake in order to be able to build the ccmark dependency. Sorry for the confusion!

**Comment by ishaanSejwal** [comment]
@chriseidhof I do have cmake. Infact on `brew install cmake` I get `Warning: cmake-3.7.1 already installed`

**Comment by chriseidhof** [comment]
Hm, then I was too quick, sorry ;).

I'm not a cmake expert, but it seems like it's missing a flag: https://cmake.org/Wiki/CMake_Useful_Variables

Normally, you don't have to configure that yourself... maybe you could try configuring that?

The current version is SPM-only btw, no support for CocoaPods at the moment...

**Comment by ishaanSejwal** [comment]
Hey @chriseidhof
I dont know where this issue occurs. Does is happen on cmark side or commonmark? Could you point some place to me, I would fork some experiment with some flags that I have understood. Thanks

**Comment by chriseidhof** [comment]
I'm not sure either, I think it's when building the commonmark c library that this depends on. Probably best to fork and figure it out, unfortunately I don't have time to do that :(.

**Comment by ishaanSejwal** [comment]
Cool. I'll check it out over the weekend and update here on my find.
