### ISSUE TITLE
Installing with cocopods CommonMark folder is empty

### ISSUE THREAD

**Issue by invoodoo** [chriseidhof/commonmark-swift#16]
Tried to install the CommonMark and got the Readme only file in the folder.

**Comment by chriseidhof** [comment]
There is no podspec, we only support swift package manager for now.

**Comment by ushu** [comment]
@invoodoo I did a quick fork to re-enable Pod support [here](https://github.com/ushu/commonmark-swift/tree/add-podspec).

You can reference it in your `Podfile` as such:
```ruby
pod "CommonMark", git: "https://github.com/ushu/commonmark-swift", branch: "add-podspec"
```

It's not deeply tested, but it build on my machine and was sufficient for my needs (mostly play with stuff in episode S01E02 of Swift Talk).

@chriseidhof: what's the rationale behind not supporting Cocoapods ? Is there hope for a PR or is it a no-go for some reason ?

_(Edit: I just saw I am 6 months late 😯)_

**Comment by Kros-s** [comment]
@ushu i'm wondering the same for now, since SPM had not support officially for iOS makes no sense to me, to being removed from Pods, @chriseidhof is there any other way to run this ? with SPM for an iOS target ?

**Comment by chriseidhof** [comment]
Closing this for now, we don't support CocoaPods but instead use SPM.
